jaffle_shop:
  target: prod
  outputs:
    prod:
      type: snowflake
      warehouse: WILMAR_ANALYTICS_DEMO_WH
      database: WILMAR_ANALYTICS_DEMO_DB
      schema: PROD
      role: WILMAR_ANALYTICS_DEMO_ROLE
      threads: 8
    dev:
      type: snowflake
      warehouse: WILMAR_ANALYTICS_DEMO_WH
      database: WILMAR_ANALYTICS_DEMO_DB
      schema: DEV
      role: WILMAR_ANALYTICS_DEMO_ROLE
      threads: 8